name = ""
account_id = ""
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023-08-22"
compatibility_flags = [ "streams_enable_constructors", "transformstream_enable_standard_constructor" ]

[site]
bucket = ".output/public"
